# Generated by Django 5.0 on 2023-12-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testgetornew",
            name="name2",
            field=models.CharField(default="123", max_length=100),
            preserve_default=False,
        ),
    ]
