# Generated by Django 5.0 on 2023-12-27 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0002_testgetornew_name2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testgetornew",
            name="name2",
        ),
    ]
