# Generated by Django 5.0 on 2023-12-28 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0003_remove_testgetornew_name2"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TestGetOrNew",
            new_name="ImplementedGetOrNew",
        ),
    ]
