# Generated by Django 5.0 on 2023-12-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("test_app", "0004_rename_testgetornew_implementedgetornew"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImplementedModelWithTimestamps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info_timestamp", models.DateTimeField()),
                ("info_modified_timestamp", models.DateTimeField()),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
